name: unicorn-binance-websocket-api
dependencies:
- python>=3.6.1
- pip:
  - cheroot
  - colorama
  - flask
  - flask_restful
  - pathlib
  - psutil
  - requests
  - ujson
  - unicorn-fy
  - websocket-client
  - websockets==10.0