blank_issues_enabled: true
contact_links:
  - name: UNICORN Devs Chat
    url: https://t.me/unicorndevs
    about: Chat with the community via the UNICORN Binance WebSocket API and ask general questions.
  - name: UNICORN Binance WebSocket API Discussions
    url: https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/discussions
    about: Ask general questions.
  - name: UNICORN Binance WebSocket API documentation
    url: https://unicorn-binance-websocket-api.docs.lucit.tech/
    about: The complete UNICORN Binance WebSocket API documentation.
  - name: Get Professional and Fast Support
    url: https://www.lucit.tech/get-support.html
    about: Contact the LUCIT Development Team.